# This file contains configurations for the labeler workflow

python:
- LogBlog/**/*.py

html:
- LogBlog/logblog/templates/**/*.html

css:
- LogBlog/**/*.css

documentation:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- docs/*
- testsuite/docs/*

testsuite:
- testsuite/**/*

QA/QE:
- testsuite/**/*

behave:
- testsuite/**/*.py

dependencies:
- Pipfile
- Pipfile.lock
- requirements.txt

usr-feature:
- LogBlog/logblog/users/*

posts-feature:
- LogBlog/logblog/posts/*

templates:
- LogBlog/logblog/templates/**/*
